name: Deploy node 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check src node
    - uses: actions/checkout@v4
    - name: login to docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
    - name: build image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dok_node .
    - name: deploy or publish in hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/dok_node

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: pull image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/dok_node
    - name: delete image older
      run: docker rmi -f dok_node_container || true
    - name: run image dok_node_container
      run: docker run -d -p 3500:3500 --name dok_node_container ${{ secrets.DOCKER_USERNAME }}/dok_node
    - name: Remove unused Docker images (optional cleanup)
      run: docker image prune -af