name: Deploy Node.js App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step checks out your source code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dok_node .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dok_node

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/dok_node

      - name: Stop and remove old container (if exists)
        run: docker rm -f dok_node_container || true

      - name: Run new Docker container
        run: docker run -d -p 3500:3500 --name dok_node_container ${{ secrets.DOCKER_USERNAME }}/dok_node

      - name: Remove unused Docker images (optional cleanup)
        run: docker image prune -af
